create table if not exists public.public_analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  session_id uuid not null,
  event_name text not null check (event_name in ('analytics_enabled', 'page_view')),
  route text not null check (route in (
    '/admin', '/business', '/catalog', '/checkout', '/driver',
    '/login', '/orders', '/other', '/pos', '/profile'
  ))
);

create index if not exists public_analytics_events_occurred_at_idx
  on public.public_analytics_events (occurred_at desc);
create index if not exists public_analytics_events_session_rate_idx
  on public.public_analytics_events (session_id, occurred_at desc);

alter table public.public_analytics_events enable row level security;
revoke all on table public.public_analytics_events from public, anon, authenticated;

create or replace function public.record_public_analytics_event(
  target_session_id uuid,
  target_event_name text,
  target_route text
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if target_session_id is null
     or target_event_name not in ('analytics_enabled', 'page_view')
     or target_route not in (
       '/admin', '/business', '/catalog', '/checkout', '/driver',
       '/login', '/orders', '/other', '/pos', '/profile'
     ) then
    return false;
  end if;

  -- Retention is enforced without an external scheduler whenever traffic arrives.
  delete from public.public_analytics_events
  where occurred_at < now() - interval '90 days';

  -- Public telemetry endpoints can be abused; cap each anonymous session.
  if (
    select count(*)
    from public.public_analytics_events
    where session_id = target_session_id
      and occurred_at >= now() - interval '1 minute'
  ) >= 60 then
    return false;
  end if;

  insert into public.public_analytics_events (session_id, event_name, route)
  values (target_session_id, target_event_name, target_route);

  return true;
end;
$$;

revoke all on function public.record_public_analytics_event(uuid, text, text) from public;
grant execute on function public.record_public_analytics_event(uuid, text, text) to anon, authenticated;

create or replace function public.delete_public_analytics_session(target_session_id uuid)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if target_session_id is null then
    return false;
  end if;

  delete from public.public_analytics_events
  where session_id = target_session_id;
  return true;
end;
$$;

revoke all on function public.delete_public_analytics_session(uuid) from public;
grant execute on function public.delete_public_analytics_session(uuid) to anon, authenticated;

comment on table public.public_analytics_events is
  'Consent-gated first-party aggregate telemetry with no direct or technical identifiers.';
